### ISSUE TITLE
Trial period starts with 0

### ISSUE THREAD

**Issue by kaishin** [justmakeapp/swiftdeps-distribution#3] opened 2023-05-25 08:28 UTC
I downloaded the app to give a try before buying but I am greeted with a trial expired pop up. I suppose this is not intentional.

**Comment by longvudai** [comment] 2023-05-25 08:42
> 
Sorry for this inconvenience.
Just kill the app and reopen it. I'll fix this bug as soon as possible.

**Comment by pdshelley** [comment] 2023-08-17 21:12
The issue is still there. Purchased anyway to try it out.

**Comment by spnkr** [comment] 2023-10-04 16:10
same issue. I bought it anyway. wish I'd tried force quitting first!

**Comment by longvudai** [comment] 2023-10-05 06:57
fixed in https://github.com/justmakeapp/swiftdeps-distribution/releases/tag/1.2.2

**Closed as completed by longvudai** 2023-10-05 06:57 UTC
Labels: bug
